FROM node:22-alpine AS frontend_builder

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend .

RUN npm run build


FROM nginx:1.27-alpine

COPY backend/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=frontend_builder /frontend/dist /usr/share/nginx/html