# Generated by Django 6.0.6 on 2026-06-30 10:31

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[accounts.validators.validate_telegram_username]),
        ),
    ]
