# Generated by Django 6.0.6 on 2026-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
