# Generated by Django 6.0.6 on 2026-06-28 09:00

import django.db.models.deletion
import live_pricing.validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('name', models.CharField(max_length=10, validators=[live_pricing.validator.validate_currency_symbol])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_baskets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('name', models.CharField(max_length=10, validators=[live_pricing.validator.validate_crypto_symbol])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_baskets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoldBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('name', models.CharField(max_length=10, validators=[live_pricing.validator.validate_gold_symbol])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_baskets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.DecimalField(decimal_places=8, max_digits=20)),
                ('start_price_T', models.DecimalField(decimal_places=8, max_digits=20)),
                ('start_price_D', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cash_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='live_pricing.cashbasket')),
                ('crypto_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='live_pricing.cryptobasket')),
                ('gold_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='live_pricing.goldbasket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cashbasket',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='cashbasket_unique_symbol_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cryptobasket',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='cryptobasket_unique_symbol_per_user'),
        ),
        migrations.AddConstraint(
            model_name='goldbasket',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='goldbasket_unique_symbol_per_user'),
        ),
    ]
